.TH RESUME 1 "January 2026" "Rich Goldstein" "Resume"
.SH NAME
Rich Goldstein \- Senior DevOps Engineer
.SH SYNOPSIS
richgoldstein@terrorgrump.com \| (802) 473-1010 \| www.terrorgrump.com
.SH PROFESSIONAL SUMMARY
Results-driven Senior DevOps Engineer with expertise in cloud technologies, Kubernetes, and automation.
Proficient in AWS, Kubernetes (EKS), Terraform, Jenkins, Python, Kafka, and more.
.SH EXPERIENCE
.SS NGNC CONSULTING
\*(JULY 2023 - PRESENT\)
.IP \*  Security and audit automation, Github security audit
.IP \*  AWS; SaltStack; NewRelic; Sentry; MySQL; Python (Boto3); Django; Flask
.SS ARTURO, INC.
\*(NOVEMBER 2022 - JULY 2023\)
.IP \*  Led migration from legacy Kubernetes/EKS to new clusters for scalability and performance.
.IP \*  Developed Jenkins shared libraries to consolidate deployment processes.
.SH SKILLS
.IP \*  Cloud Services: AWS (EC2, EKS, Lambda, MSK)
.IP \*  OS Platforms: Debian, Ubuntu, CentOS, Rocky Linux, Alpine
.IP \*  Programming: Bash, Python, Ruby, Go, JavaScript, Typescript
.SH EDUCATION
.B Bachelor of Science in Computer Science/Electrical Engineering, Stony Brook University
.SH CONTACT
richgoldstein@terrorgrump.com \| (802) 473-1010 \| www.terrorgrump.com

